version: '3.5'
services:

  # base ubuntu packafges for pre-build
  autobdd-ubuntu:
    build:
      context: ${PWD}/..
      dockerfile: .docker/autobdd-ubuntu.dockerfile
      args:
        AUTOBDD_VERSION: ${AUTOBDD_VERSION}
    image: "xyteam/autobdd-ubuntu:${AUTOBDD_VERSION}"
    container_name: autobdd-ubuntu

  # add non-ubuntu packages
  autobdd-nodejs:
    build:
      context: ${PWD}/..
      dockerfile: .docker/autobdd-nodejs.dockerfile
      args:
        AUTOBDD_VERSION: ${AUTOBDD_VERSION}
    image: "xyteam/autobdd-nodejs:${AUTOBDD_VERSION}"
    container_name: autobdd-nodejs

  # main container for build and pull/push
  autobdd:
    build:
      context: ${PWD}/..
      dockerfile: .docker/autobdd-image.dockerfile
      args:
        AUTOBDD_VERSION: ${AUTOBDD_VERSION}
    image: "xyteam/autobdd:${AUTOBDD_VERSION}"
    container_name: autobdd

  # dev container for developing autobdd test
  autobdd-dev:
    image: "xyteam/autobdd:${AUTOBDD_VERSION}"
    container_name: autobdd-dev
    shm_size: 1536M
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:delegated
      - ${HOME}/${ProjectsBase:-Projects}:/home/${USER}/Projects:delegated
    ports:
      - "5922:5900"
      - "2222:22"
      - "8002:8000"
    environment:
      - USER=${USER}
      - USERID=${USERID}
      - GROUPID=${GROUPID}
      - HOSTOS=${HOSTOS}
      - PASSWORD=${PASSWORD}
      - VNC_PASSWORD=${VNC_PASSWORD}
      - RESOLUTION=1920x1200x24
      - ABDD_PROJECT=${ABDD_PROJECT}
    entrypoint: "/root/autobdd-dev.startup.sh"

  # run container for running autobdd test
  autobdd-run:
    image: "xyteam/autobdd:${AUTOBDD_VERSION}"
    container_name: autobdd-run
    shm_size: 1536M
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:delegated
    environment:
      - USER=${USER}
      - USERID=${USERID}
      - GROUPID=${GROUPID}
      - HOSTOS=${HOSTOS}
      - ABDD_PROJECT=${ABDD_PROJECT}
    entrypoint: "/root/autobdd-run.startup.sh"

