# run test with autobdd-run
# docker-compose run --rm autobdd-run "make test-all"
#
# spin up autobdd-dev for test development:
# docker-compose up -d autobdd-dev
# docker-compose logs -f autobdd-dev
# ssh localhost -p 2222
# vnc localhost:5922
# 
version: '3.5'
services:

  # main container for build and pull
  autobdd:
    build:
      context: ${HOME}/${ProjectsBase:-Projects}/AutoBDD
      dockerfile: .docker/autobdd.dockerfile
      args:
        AutoBDD_Ver: ${AutoBDD_Ver}
    image: "xyteam/autobdd:${AutoBDD_Ver}"
    container_name: autobdd

  # dev container for developing autobdd test
  autobdd-dev:
    image: "xyteam/autobdd:${AutoBDD_Ver}"
    container_name: autobdd-dev
    shm_size: 1536M
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:delegated
      - ${HOME}/${ProjectsBase:-Projects}:/home/${USER}/Projects:delegated
    ports:
      - "5922:5900"
      - "2222:22"
      - "8002:8000"
    environment:
      - USER=${USER}
      - BDD_PROJECT=${BDD_PROJECT}
      - HOSTOS=${HOSTOS}
      - USERID=${USERID}
      - GROUPID=${GROUPID}
      - PASSWORD=${PASSWORD}
      - VNC_PASSWORD=${VNC_PASSWORD}
      - RESOLUTION=1920x1200x24
    entrypoint: "/root/autobdd-dev.startup.sh"

  # run container for running autobdd test
  autobdd-run:
    image: "xyteam/autobdd:${AutoBDD_Ver}"
    container_name: autobdd-run
    shm_size: 1536M
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:delegated
    environment:
      - USER=${USER}
      - BDD_PROJECT=${BDD_PROJECT}
      - HOSTOS=${HOSTOS}
      - USERID=${USERID}
      - GROUPID=${GROUPID}
    entrypoint: "/root/autobdd-run.startup.sh"
